[package]
name = "fppa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "0.5.0"
tempdir = "0.3.7"
rand = "0.8.5"
strum = "0.24"
strum_macros = "0.24"